### ISSUE TITLE
Webpack -  Module not found: Error: Cannot resolve module 'nvd3' in node_modules\angular-nvd3\dist

### ISSUE THREAD

**Issue by ir-taimal10** [krispo/angular-nvd3#568]
Hello, I'm using the angular-nvd3 library in a project,  I use webpack to manage dependencies, my application was functioning normally but today I get this error:

ERROR in ./~/angular-nvd3/dist/angular-nvd3.js
Module not found: Error: Cannot resolve module 'nvd3' in node_modules\angular-nvd3\dist
 @ ./~/angular-nvd3/dist/angular-nvd3.js 13:13-28

you can give me an idea about the solution?

**Comment by ir-taimal10** [comment]
I added this dependence in my project  and the problem was solved.       package.json  -   "nvd3": "^1.8.4"

**Comment by mennya** [comment]
We have the same issue, senks for your workaround, it helps.

**Comment by WillySchu** [comment]
We also have the same issue, adding nvd3 as a project dependency has not resolved it.

**Comment by juandjara** [comment]
The problem here is that the nvd3 package in npm does not export the nv variable
I fixed this by defining an alias in the webpack config

``` js
resolve: {
  alias: {
    nvd3: "nvd3/build/nv.d3.min.js"
  }
}
```

So now i can do `import 'nvd3'` and the `nvd3` code puts `nvd3` into `window.nv` but the `angular-nvd3` code requires it again using `nv = require('nvd3')` so it gets overwritten with a blank object

Any clue on how to continue ?

**Comment by johncomposed** [comment]
Looks like something happened with the nvd3 package, which says it was updated 6 days ago. 

Weirdly, `npm view nvd3` shows that version 1.8.4 exists, just is treated as an earlier version than 1.7.1 (the "latest" and also what angular-nvd3 depends on).

As a temporary workaround, installing `nvd3@1.8.4` worked for me.

**Comment by juandjara** [comment]
Well, that solved the problem for me. Thanks a lot, @johncomposed ! :+1:
